import type { ScanReport } from "./types.js";

export function renderMarkdown(report: ScanReport): string {
  const findings = report.findings.length
    ? report.findings
        .map(
          (finding) => [
            `### ${badge(finding.level)} ${finding.title}`,
            "",
            `**Rule:** \`${finding.id}\``,
            `**Why:** ${finding.reason}`,
            `**Evidence:** ${finding.evidence.map((item) => `\`${item}\``).join(", ")}`,
            `**Recommendation:** ${finding.recommendation}`
          ].join("\n")
        )
        .join("\n\n")
    : "No findings detected.";

  const requiredActions = report.requiredActions.length
    ? report.requiredActions.map((action) => `- ${action}`).join("\n")
    : "- No blocking actions from policy.";

  return [
    "## AI Maintainer OS Review",
    "",
    `**Risk:** ${badge(report.level)} ${report.level.toUpperCase()}`,
    `**Score:** ${report.score}/100`,
    `**Summary:** ${report.summary}`,
    "",
    "### Required Actions",
    requiredActions,
    "",
    "### Findings",
    findings,
    "",
    "### Changed Files",
    report.changedFiles.map((file) => `- \`${file}\``).join("\n") || "- None",
    "",
    "### Maintainer Note",
    report.maintainerNote,
    "",
    "---",
    "Generated by AI Maintainer OS. This report is a review aid, not a replacement for human maintainer judgment."
  ].join("\n");
}

export function renderJson(report: ScanReport): string {
  return `${JSON.stringify(report, null, 2)}\n`;
}

function badge(level: string): string {
  if (level === "critical") return "[CRITICAL]";
  if (level === "high") return "[HIGH]";
  if (level === "medium") return "[MEDIUM]";
  return "[LOW]";
}
